moveit_servo:
  ros__parameters:
    move_group_name: "fr3_arm"
    planning_frame: "fr3_link0"
    ee_frame_name: "robotiq_85_base_link"
    robot_link_command_frame: "fr3_link0"

    # command_in_type: "speed_units"
    # command_out_type: "std_msgs/Float64MultiArray"
    # command_out_topic: "/fr3_velocity_controller/commands"


    command_in_type: "twist"
    command_out_type: "trajectory_msgs/JointTrajectory"
    command_out_topic: "/fr3_arm_controller/joint_trajectory"

    publish_period: 0.02
    low_latency_mode: false
    incoming_command_timeout: 0.1
    

    # publish_joint_positions: false
    # publish_joint_velocities: true
    # publish_joint_accelerations: false

    check_collisions: true
    collision_check_rate: 20.0
    # lower_collision_proximity_threshold: 0.02
    # hard_stop_collision_proximity_threshold: 0.005

    linear_scale: 0.01
    rotational_scale: 0.01
    joint_scale: 0.8


    joint_names:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

    use_gazebo: false
