moveit_servo:
  ros__parameters:
    move_group_name: fr3_arm
    planning_frame: fr3_link0
    ee_frame_name: robotiq_85_base_link
    robot_link_command_frame: fr3_link0

    joint_topic: /joint_states

    command_in_type: twist
    cartesian_command_in_topic: /moveit_servo/delta_twist_cmds
    command_out_type: trajectory_msgs/JointTrajectory
    command_out_topic: /fr3_arm_controller/joint_trajectory

    publish_period: 0.01
    incoming_command_timeout: 0.1
    low_latency_mode: false

    check_collisions: true
    collision_check_rate: 10.0
    scale:
      linear: 0.5
      rotational: 0.5
      joint: 0.8

    joint_names:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

    use_gazebo: false
