/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      robotiq_gripper_controller:
        type: position_controllers/GripperActionController

/**:
  robotiq_gripper_controller:
    ros__parameters:
      joint: robotiq_85_left_knuckle_joint
      goal_tolerance: 0.01
      stalled_velocity_threshold: 0.01
      stall_timeout: 0.2
      allow_stalling: true
